### ISSUE TITLE
How about Mac with Apple M1

### ISSUE THREAD

**Issue by satan-j** [NeptuneProjects/TritonOA#1]
In 2.Preparation.C, I can't find its Intel CPU model name. After 4.3, it will exist errors.Do you have the solution to that?

**Comment by NeptuneProjects** [comment]
Your Mac doesn't have an Intel CPU, it has an M1 CPU, so it doesn't meet the initial conditions of my procedure and step 2 isn't applicable to your computer. The M1 is Apple's proprietary chipset that replaced Intel CPUs in 2020.

I don't have one of the newer Macs so I can't be certain, but you could try using the GNU Fortran compiler `GFortran` (https://gcc.gnu.org/fortran/). The default makefile in Acoustics Toolbox has one or two `gfortran` compile commands uncommented, so it should work as long as you comment out the other compiler commands (for instance, some of the `ifort` compiler commands need to be commented out).
